# Site settings
title: Hacker Wagon - Redefining Cybersecurity Trainings
description: Hacker Wagon - Redefining Cybersecurity Trainings
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hacker Wagon
user_description: Hacker Wagon bootcamps are revolutionary and brings to you the best of ancient gurukul style learning and gives it a modern twist. With ample technical know how and a deep understanding of people in the cyber sphere and the problems they face. Our team will ensure that your first steps to your path in this industry will be a fun filled and collaborative experience.
#user_title: Bootcamp for Hackers!!
#email: info@hackerwagon.com
#twitter_username: HackerWagon
#linkdin_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
