# Site settings
title: Hacker Wagon - Redefining Cybersecurity Trainings
description: Hacker Wagon - Redefining Cybersecurity Trainings
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hacker Wagon
user_description: We at Hacker Wagon aim to revolutionize the world of Cyber Security trainings in a unique manner. Our team has a deep technical experience in the field of Information Security and expertise ranging from Penetration testing to Digital Forensics & Incident Response. With ample technical know how and a deep understanding of people in the cyber sphere and the problems they face. The team at Hacker Wagon has designed a unique bootcamp experience, that will help you take your first steps on your path in a fun and collaborative manner.
user_title: Cybersecurity Trainings for the New Generation!!
#email: info@hackerwagon.com
#twitter_username: HackerWagon
#linkdin_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
